services:
  app:
    container_name: app_container_prod
    build:  .
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped