version: '3'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - PGDATA=/data/postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "app", "-U", "postgres" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 80s  
  app:
    container_name: app_container
    build:  .
    env_file: ./oauth42.env
    environment:
      - NODE_ENV=production
      - POSTGRES_URL
      - SESSION_SECRET
    ports:
      - "80:3000"
    networks:
      - postgres
    depends_on:
        postgres:
          condition: service_healthy
    restart: unless-stopped

networks:
  postgres:

volumes:
    postgres:
