services:
  app:
    container_name: app_container_dev
    image: node:19.2-bullseye
    volumes:
      - .:/workspace:cached
      - vscode_extensions:/root/.vscode-server/extensions
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports: 
      - 3000:3000
      - 5173:5173
    environment:
      NODE_ENV: development

volumes:
  vscode_extensions:
