export enum InvalidCacheTarget {
  DIRECT_MESSAGE,
  BLOCK_USER,
  INVITATION_FRIEND,
  REFUSE_INVITATION_FRIEND,
  UPDATE_USER_NAME,
  FRIEND_USER,
  UNFRIEND_USER,
  CANCEL_INVITATION,
  UNBLOCK_USER,
  READ_DIRECT_MESSAGE,
  // CHANNEL_MESSAGE,
  // CHANNEL_INVITATION,
}
